### ISSUE TITLE
Reloading

### ISSUE THREAD

**Issue by classified** [Yalantis/Segmentio#1]
How to reload Segmentio? Currently i'm re intializing everything and it won't show the first default selected indicator for some reason.

EDIT: 

I have done the Indicator part just needed to call `moveShapeLayerAtContext()` in `setup` method to show indicator.

**Comment by houze2311** [comment]
Hi @classified! Thanks for reporting the issue. Could you describe steps to reproduce the bug?

**Comment by AnnieNinaJoyceV** [comment]
I had a similar issue. Say, I have 4 view controllers added to segmentio. The very first time I take data from local cache storage, if there is any. Meanwhile in the background I hit the API and fetch data, once done I need to refresh my controller's tableview/collectionview to show the updated data. I made the `reloadSegmentio` method public and called it from my class and that worked fine. But I would like to know if there is any other alternative to fix this?

**Comment by bryanbartow** [comment]
I have this same issue. Making the ```reloadSegmentio``` method public should do the trick.

**Comment by FredvanRijswijk** [comment]
@AnnieNinaJoyceV @bryanbartow How did you use it... 4 viewcontrollers, they all load when opening the view with Segmentio... ?
