### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by AfrozZaheer** [Yalantis/Segmentio#102]
# Report

**a feature request** 
## A feature request
RTL support 

###  What do you want to add?
Currently Segmentio scroll is not adjustable in RTL views. I want it to automatically support the scroll direction 

### Your Environment

- Version of the component: _4_
- Swift version: _4.2_
- iOS version: _11.4_
- Device: _iPhone X_
- Xcode version: _Xcode 9.4.1_
### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : bitbucket-jetsrewardspod - https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git @ d536a626db7584b2aea79244a16672f4f556bd39
               master - https://github.com/CocoaPods/Specs.git @ c16dcc667abff3c3e1e52cebb1280ce19b5999f7
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

` and insert here_

**Comment by AfrozZaheer** [comment]
Never mind solve it with this.... 

extension UICollectionViewFlowLayout { // For RTL scrolling
    
    open override var flipsHorizontallyInOppositeLayoutDirection: Bool {
        return true
    }
}

**Comment by hendksoliman** [comment]
how can i use it please ?

**Comment by hendksoliman** [comment]
@AfrozZaheer  how can i use it ?

**Comment by AfrozZaheer** [comment]
@hendksoliman this method just flip the collection view in segemntio... just override the classes of segmentio view... or if you don't want to mess around use https://github.com/Yalantis/Segmentio/pull/122 
this commit code for proper RTL use...

**Comment by nvdmcs** [comment]
there is bug of selected Item background color is disturb. RTL Support In APP, so i reinstall pod > 4 to old pod version 3.2. and handling RTL in app,  manually.
