### ISSUE TITLE
Wrong version in cocoapods repo ?

### ISSUE THREAD

**Issue by Deub27** [Yalantis/Segmentio#103]
# Report

Hi, Cocoapods.org seems to still have Segmentio v3.0

I had to set my Podfile like this in order to have latest release (3.1)

pod 'Segmentio', :git => 'https://github.com/Yalantis/Segmentio', :branch => 'master'
rather than
pod 'Segmentio', '~> 3.1'

**Comment by rnkyr** [comment]
updated, sorry for inconvenience
