### ISSUE TITLE
Lost text in segment control when using navigationBar.prefersLargeTitles (IOS 11)

### ISSUE THREAD

**Issue by leewonghao** [Yalantis/Segmentio#105]
###  What did you do?

   Lost label content in segment when using navigationBar.prefersLargeTitles = true.
   Please help me.

### Your Environment

- Swift version: 4.2
- iOS version: 11
- Device: iPhone X
- Xcode version: 9

<img width="331" alt="screen shot 2018-09-12 at 12 28 47 am" src="https://user-images.githubusercontent.com/8869627/45376755-d4322700-b622-11e8-8796-54c88b1f7cd6.png">

**Comment by rnkyr** [comment]
dup of #83
