### ISSUE TITLE
wrong position for indicatorLayer and selectedLayer when using dynamic position

### ISSUE THREAD

**Issue by LijunWu** [Yalantis/Segmentio#106]
###  What did you do?

> When I set `SegmentioPosition = .dynamic`, the position of `indicatorLayer` and `selectedLayer` are wrong.  Calculate `spaceBefore` In the initialize method method for `Segmentio.Points`  using the same `cellWidth` not dynamic width.

![2018-09-12 4 26 38](https://user-images.githubusercontent.com/8665513/45412186-a8f21b00-b6a8-11e8-9d32-1d7ae67ff101.png)

**Comment by rnkyr** [comment]
closed via #
