### ISSUE TITLE
Landscape to Portrait button position change layout issue

### ISSUE THREAD

**Issue by ajoykarmakar459** [Yalantis/Segmentio#131]
Firstly I want to congratulate for this awesome plugin. It's really working perfectly but I am facing issue in layout while landscaping to the potrait mode, the segment button position change. If I click only another button the button position is looking good but firstly it looks quite odd because of the position.

**Screenshot -**

Before rotating (portrait)-
https://i.ibb.co/xhG0zJf/Screen-Shot-2019-06-22-at-4-05-12-PM.png

After Rotating (Landscape)
https://i.ibb.co/34Khc3d/Screen-Shot-2019-06-22-at-4-05-22-PM.png

After again rotating (portrait), **The issue is here**-
https://i.ibb.co/mv7HKqw/Screen-Shot-2019-06-22-at-4-05-36-PM.png

After clicking another button fix the layout (portrait)-
https://i.ibb.co/94FKNKC/Screen-Shot-2019-06-22-at-4-05-43-PM.png

**My Environment - **
- Swift version: 5
- iOS version: 12
- Device: iPhone 6 Simulator 
- Xcode version: 10.2.1
 'Segmentio version:  3.3

**Comment by christianvershkov** [comment]
It was fixed in this pull request #123  Check it when it is merged

**Comment by rnkyr** [comment]
closed via #123
