### ISSUE TITLE
Larger word overbounds contentView

### ISSUE THREAD

**Issue by LeonardoCardoso** [Yalantis/Segmentio#16]
###  What did you do?

I used a long word.

### What did you expect to happen?

Truncate the word.

### What happened instead?

When the word is larger than the contentView, it overbounds.
![screen shot 2016-11-07 at 00 03 24](https://cloud.githubusercontent.com/assets/1775157/20045238/315135ba-a47e-11e6-8d69-9b59b25c9876.png)

### Solution

I've solved it adding this line right after this block [SegmentioCell.swift#L183-L192](https://github.com/Yalantis/Segmentio/blob/34cf755361b490bdea8699bcbd6a4eb267de1e24/Segmentio/Source/Cells/SegmentioCell.swift#L183-L192):

```swift 

segmentTitleLabel.leadingAnchor.constraint(equalTo: containerView.leadingAnchor, constant: 5).isActive = true

```

![screen shot 2016-11-07 at 00 03 33](https://cloud.githubusercontent.com/assets/1775157/20045243/3a407e74-a47e-11e6-98e0-22cf3d9800b1.png)
![screen shot 2016-11-07 at 00 03 39](https://cloud.githubusercontent.com/assets/1775157/20045244/3a416366-a47e-11e6-808a-133674012edc.png)

**Comment by IgorMuzyka** [comment]
@LeonardoCardoso  please check if the latest code works for you and if yes please close the issue.
Install *Segmentio* via cocoapods like this:
`pod 'Segmentio', :git=> 'git@github.com:Yalantis/Segmentio.git'`

**Comment by LeonardoCardoso** [comment]
Ok. I'll have a look.

**Comment by serejahh** [comment]
Hi @LeonardoCardoso. Any news about the issue?

**Comment by LeonardoCardoso** [comment]
It didn't work for me. I had to use my solution.
