### ISSUE TITLE
AnimatioDuration parameter is not in the last pod 2.0

### ISSUE THREAD

**Issue by jarrillaga** [Yalantis/Segmentio#18]
Can you check the last pod?

SegmentioOptions(
    backgroundColor: UIColor.whiteColor(),
    maxVisibleItems: 3,
    scrollEnabled: true,
    indicatorOptions: SegmentioIndicatorOptions,
    horizontalSeparatorOptions: SegmentioHorizontalSeparatorOptions,
    verticalSeparatorOptions: SegmentioVerticalSeparatorOptions,
    imageContentMode: UIViewContentMode.Center,
    labelTextNumberOfLines: 1,
    labelTextAlignment: NSTextAlignment.Center,
    segmentStates: SegmentioStates, // tuple of SegmentioState (defaultState, selectState, highlightedState)
    animationDuration: 0.1
)

**Comment by houze2311** [comment]
@jarrillaga Today I plan to update the Pod

**Comment by houze2311** [comment]
fixed example, ver 2.1
