### ISSUE TITLE
Autolayout issues

### ISSUE THREAD

**Issue by jarrillaga** [Yalantis/Segmentio#19]
I had copyed the example in my own project. I´m using autolayout and storyboards. Please check the image. I hava a problem that the cells don´t start at the top.

![simulator screen shot nov 8 2016 17 39 12](https://cloud.githubusercontent.com/assets/11060950/20116279/6aeff826-a5da-11e6-9ff7-01d0e451888b.png)

**Comment by houze2311** [comment]
@jarrillaga please check top space contain for SegmentioView in your project also you can check option for viewController in storyboard:
Extend Edges -> Under top bar: false

**Comment by jarrillaga** [comment]
@houze2311 Cheers mate.... the Extend Edges -> Under top bar: false fixed the problem. I think you should add this condition when usign storyboards.
