### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by LeandroHub** [Yalantis/Segmentio#21]
###  What did you do?

I downloaded the zip file from GitHub and opened the Segmentio.xcworkspace file inside the Example folder. 

### What did you expect to happen?

I expected to see the example running in the Simulator. 

### What happened instead?

An issue appears when compiling and can't run the application. The issue is in the class ExampleViewController.swift, line 95, inside the function: fileprivate func segmentioOptions() -> SegmentioOptions. The error says: "Expression type 'SegmentioOptions' is ambiguous without more context"

### Your Environment

- [x] Swift version: the one in the example project.
- [x] iOS version: last version
- [x] Device: simulator
- [x] Xcode version: 8.1

Thanks in advance!

**Comment by houze2311** [comment]
Hi
I can load Segmentio from branch `issues_fixes` with fixes for Segmentio's core and example

**Comment by LeandroHub** [comment]
Thanks @houze2311 for your fast response! The example works great using that branch! 

Best regards!
