### ISSUE TITLE
Is it possible to change the image when selection is done?

### ISSUE THREAD

**Issue by jarrillaga** [Yalantis/Segmentio#22]
Is it possible to change the image when selection is done? I.E: We have three with icons but I want to put in red the one that is selected. I know that the selection indicator can do it but I want to change the image too.

**Comment by jarrillaga** [comment]
I found a way to change the image. In the callback of the sectedSegmetioIndex, I call again the setup method with the new images. The problem that I have is that the selection indicator disappears.

Any idea? Thanks :)

**Comment by jarrillaga** [comment]
Anyone is supporting this library anymore?

**Comment by houze2311** [comment]
Hi @jarrillaga
Yalantis team been supporting all library and components.
I have prepared fixes () for the open issues (branch `issues_fixes`) and I going to update the Segmentio in the near future.
Also I have an aim to add the ability to use images for different states and other improvements.
This is an open source project, you can also give your part.

**Comment by jarrillaga** [comment]
Hi @houze2311, 

I´ll be glad to help in new features. Your control works great. I´ll let you know in case I code a new functionality.

Cheers, Juan
