### ISSUE TITLE
Multiple datasource / Views

### ISSUE THREAD

**Issue by FredvanRijswijk** [Yalantis/Segmentio#23]
I have implement Segmentio, it's awsome, but don't understand how to feed every tab/segment with a datasource... I want to feed the tableview with an other query to my database, but I can see that there is a callback on selected segment, but thats not the place to update my query on the tableview datasource... Somebody use this with an async datasource or I have to make all data available when you open de segmentio view..?

That will be al lot of data...  

And use it to view different views, like events, information and pricelist for example? Is that possible or not?

**Comment by FredvanRijswijk** [comment]
@serejahh can you help me in the right direction?

**Comment by houze2311** [comment]
Hi
I designed Segmentio as control.
You can make fork and update logic for `UICollectionViewDataSource` in `Segmentio.class`.
As an option you can add open `var segmentioDataSource: UICollectionViewDataSource` and setup it in you `UIViewController` and update some logic in `Segmentio.class`.
