### ISSUE TITLE
setupContent issue from documentation.

### ISSUE THREAD

**Issue by kwstasna** [Yalantis/Segmentio#24]
Hello.
Today I tried to add Segmentio in my project but i'm dealing with an issue.
I make a view inside my view controller and I give it a custom class `Segmentio`

http://imgur.com/a/9VlYy

and i get an error that 
Segmentio has no member `setupContent`

http://imgur.com/a/Gmome

Any idea?

### Your Environment

- Version of the component: _2_
- Swift version: _3_
- iOS version: _10.1_
- Device: _iPhone SE_
- Xcode version: _Version 8.1 (8B62)_
- If you use Cocoapods: _### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12.1 (16B2327e)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 44f6d124c70edebd45d34829a46eefb2c0154799
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
_

**Comment by surayashivji** [comment]
Also having this issue

**Comment by surayashivji** [comment]
You should change 'setupContent' to 'setup' -- If you look at the Segmentio class you'll see this change (Swift 3 migration). 😃

**Comment by kwstasna** [comment]
@surayashivji yes that's true. opening another issue cause nothing works actually ! :cry:
