### ISSUE TITLE
Underline not working when selecting programmatically

### ISSUE THREAD

**Issue by perroyverde** [Yalantis/Segmentio#25]
# Underline not working when selecting programmatically
### Your Environment

- Version of the component: 'Segmentio', '~> 2.0'
- Swift version: 3
- iOS version: 10.x
- Xcode version: 8.0

I've tried setting `self.selector.selectedSegmentioIndex = 0` but underlining is not showing up until I click in another item on the list.

**Comment by kwstasna** [comment]
Could you upload an example cause i managed to finish mine yesterday and had no issues at all. even in a test that i did, there was an underline!

**Comment by perroyverde** [comment]
Corrected in the last version. Closing issue 👍
