### ISSUE TITLE
Expression type SegmentioOptions is ambiguous without more context

### ISSUE THREAD

**Issue by surayashivji** [Yalantis/Segmentio#26]
# Report

> The more information you provide, the faster we can help you.

When building the example project, I receive a compile error on line 95 of ExampleViewController.swift.

⚠️ Select what you want *report a bug**

###  What did you do?

> Tried to build the examples repository

### What did you expect to happen?

> Compile

### What happened instead?

> Received an error in the `ExampleViewController.swift` on line 95. Expression type type `SegmentioOptions` is ambiguous without more context.

### Your Environment

- Version of the component: Most recent
- Swift version: 3
- iOS version: 10
- Device: Simulators
- Xcode version: 8

### Project that demonstrates the bug

Examples in the current github project

**Comment by kwstasna** [comment]
try this branch

https://github.com/Yalantis/Segmentio/tree/issues_fixes

**Comment by surayashivji** [comment]
Thank you!

**Comment by surayashivji** [comment]
Thank you!

**Comment by surayashivji** [comment]
Any idea how to fix it within SegmentioBuilder.swift itself? Having difficulties integrating the file into my own project without getting the ambiguity error.

**Comment by serejahh** [comment]
Isn't it fixed in the latest version?

**Comment by kwstasna** [comment]
@serejahh with the latest version `pod 'Segmentio', '~> 2.1'` i've managed to make it work though.

**Comment by serejahh** [comment]
Sounds great 👍

**Comment by bryanbartow** [comment]
I'm having this issue even when using the latest version of the pod.

**Comment by serejahh** [comment]
Hi @bryanbartow! Could you provide a demo project all describe more details?

**Comment by bryanbartow** [comment]
@serejahh My fault. I didn't realize there were more parameters to pass into the initializer now. Once I passed them in it works fine. Sorry for the false alarm.
