### ISSUE TITLE
Bring to Front function, breaks segmentio.

### ISSUE THREAD

**Issue by kwstasna** [Yalantis/Segmentio#45]
###  What did you do?

Let's say that we have a table view at views full width and height.
Below it we place a segmentio view, which is hidden.
When a tab bar item button is pressed, i make the segmentio view unhidden and with the function

self.view.bringSubview(toFront: self.segmentioView)

I make the segmentioview to come at the top of the table view.
Although the segmentio view appears, is broken. The segmentioview does not contain any images or handles any tap functionality.
Any idea why?

### Your Environment

- Version of the component: _2.1.2_
- Swift version: _3_
- iOS version: _10_
- Device: _iPhone SE_
- Xcode version: _8.1 8B62_
- If you use Cocoapods: _### Stack
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12.1 (16B2327e)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2e756db0314bf29638c785bdb50ce05cb6db539e
               master copy - https://github.com/CocoaPods/Specs.git @ aeafd7f34b8140089f4d1a10db670cac1d6e8b27
### Installation Source
Executable Path: /usr/local/bin/pod
### Plugins
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 2.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
### Podfile
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Events Near Me' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RealmSwift'
    pod 'Alamofire', '~> 4.0’
    pod 'Segmentio', '~> 2.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' 
    end
  end
end_ 

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by SerjOxo** [comment]
@kwstasna Hello, thank for your report. I was trying to repeat your problem, but it works. It seems that you are doing something wrong. Can you describe your problem more informative?

**Comment by rnkyr** [comment]
If this issue is still happening please let us know.
