### ISSUE TITLE
Is there any functionality to create tabs with different widths?

### ISSUE THREAD

**Issue by Gurbo** [Yalantis/Segmentio#46]
Is there any functionality to create tabs with different widths? For example I need to create 3 tabs with such texts: "All", "BlaBlaBlaBlaFilms", "Horror" and want to see it like this:

## | All | BlaBlaBlaBlaFilms | Horror |

and not in a such way:

## | -------All----------| BlaBlaBlaBlaFilms |-------Horror---------| 

 Thanks @YuryGrinenko @edBaev @constantineSafronov  @dimazen @sfes @serejahh

**Comment by serejahh** [comment]
Hi @Gurbo. Unfortunately, it can't be done now, but we're open for PRs

**Comment by maxcampolo** [comment]
@serejahh @Gurbo Hey all I have an open PR for dynamic sizing that I opened a couple months ago that has not been merged, #34. Is there anything else that would need to be done so it could be merged?

**Comment by rmvz3** [comment]
That would be an useful option. Please, consider merging @maxcampolo PR.

**Comment by rmvz3** [comment]
I've been testing @maxcampolo version and it works great. Still not what I'd need tho :( 
Ideally I'd want text sized label widths with scroll instead of adjusting the labels proportionally to view statically. Text size indicator instead of label size will be great too.

**Comment by maxcampolo** [comment]
@rmvz3 scrolling is supported when the total length of the segment labels is greater than the width of the segmentio. Did you set it up with the `.dynamic` option?

**Comment by rmvz3** [comment]
@maxcampolo OMG, my fault (again). It turns the elements (from a Web service) just fit perfectly in the view and I assumed they were shrunken. Definitely not my day. Sorry. I'm going to try to force a little more space between labels tho.

![captura 2017-04-05 a las 23 47 45](https://cloud.githubusercontent.com/assets/674750/24728646/1b4ce176-1a5b-11e7-83e5-a90343bbfd33.png)

Thanks again. Great work.

**Comment by MiteshiOS** [comment]
@rmvz3  In which file or where i need to do change for dynamic width of single segment ?

**Comment by rmvz3** [comment]
@MiteshiOS Hi. I ended using @maxcampolo's version from https://github.com/maxcampolo/Segmentio

**Comment by MiteshiOS** [comment]
@maxcampolo can you please help me on this. I downloaded code from link provided by @rmvz3. But i can't found where i need to change for dynamic width of label.

**Comment by Shawnees** [comment]
Do ppl have new about this PR ?

**Comment by rnkyr** [comment]
closing the issue since #34 already merged. thanks, everyone!
