### ISSUE TITLE
Top and bottom black lines are displayed unconditionally

### ISSUE THREAD

**Issue by gooooer** [Yalantis/Segmentio#5]
There is an issue with your example. I've just cloned repo and run it and here's what I see:
<img width="189" alt="screenshot at sep 02 16-36-27" src="https://cloud.githubusercontent.com/assets/1442372/18205603/891ee368-712b-11e6-9218-775fb1103240.png">

There are black lines at top and bottom of Segmentio while nothing is on GIF-demo. Could you please clarify is it a bug or feature? And in case if it's feature - let me know how to disable it?

**Comment by serejahh** [comment]
Hi @gooooer. Thanks for interest to out component!

I cloned and didn't see the line (it mustn't be there). @houze2311, could you also check it?

**Comment by gooooer** [comment]
Hi @serejahh . I'm running Xcode 7.3.1, iPhone 6s simulator with iOS 9.3 on board. I'm also able to see those two black lines even if I just put Segmentio to Interface Builder (i.e. add UIView and assign Segmentio class to it)

**Comment by chenyuan** [comment]
I'm facing the similar issue after upgraded to 1.0. For my case, I put the segmentio down the bottom of a view, then I got two horizontal lines at the top of the view. I reckon that's the horizontal separators.

downgraded the version to 0.15 fixed the issue.

**Comment by AnnieNinaJoyceV** [comment]
Acknowledge having the same issue

**Comment by PravdaEvgen** [comment]
Hello, guys! Check new version 1.1

**Comment by AnnieNinaJoyceV** [comment]
Fixed 👍 Thank you!
