### ISSUE TITLE
Scroll the segmentio right to where contentoffset.x == 2*itemWidth

### ISSUE THREAD

**Issue by blackchena** [Yalantis/Segmentio#52]
###  What did you do?

Scroll the segmentio right to where contentoffset.x == 2*itemWidth, keep dragging ,scroll the viewcontroller.scrollview ,shaplayer and indicator layer's location is wrong. There is some shrink when continue scroll segmentio at previous condition.

**Comment by SerjOxo** [comment]
@blackchena Hi, thanks for your report! Can you give me more information about your issue?

**Comment by rnkyr** [comment]
If this issue is still happening please let us know.
