### ISSUE TITLE
Please add Xcode 8/Swift 3.0 support

### ISSUE THREAD

**Issue by gooooer** [Yalantis/Segmentio#6]

**Comment by serejahh** [comment]
Hi @gooooer

The issues is in progress now. Stay tuned 😃

**Comment by hdoria** [comment]
+1 !

**Comment by serejahh** [comment]
A new release will be available soon https://github.com/Yalantis/Segmentio/tree/swift3

**Comment by 128keaton** [comment]
Hi, I'm using the Swift3 branch and it seems the SegmentioStyle property is broken.

**Comment by msalihkocak** [comment]
@128keaton did you download Swift3 branch manually or used CocoaPods? If you used CocoaPods can you specify the pod text because i have updated all libraries except this one.

**Comment by grifas** [comment]
pod 'Segmentio', :git => 'https://github.com/Yalantis/Segmentio.git', :branch => 'swift3'

**Comment by 128keaton** [comment]
@msalihkocak yes, I am using the branch with Cocoapods

**Comment by LeonardoCardoso** [comment]
+1

**Comment by serejahh** [comment]
Finally it's here. Please update to `2.0`
