### ISSUE TITLE
The height of the view cannot be set under 100

### ISSUE THREAD

**Issue by NortonWEI** [Yalantis/Segmentio#64]
# Report

> The height constraint of the view of Segmentio cannot be set too small.

###  What did you do?

> I tried to add the view in two ways, both via storyboard and codes (programmatically). However, with the 1st way, when I set the height of the Segmentio View to be less than 100 (approximately), say 50, the view did not work at all, since I only want to use labels. This is the same with the 2nd way.

### What did you expect to happen?

> The view should've been functional.

### What happened instead?

> The view was just stuck without any label text and no callback will be handled. The whole view was just hung there.

### Current Solution (maybe not optimal)

> Add a view programmatically and simply add a UIView with the same size and constraints in the storyboard. The view turns out to be functional.

### Your Environment

- Version of the component: Segmentio 2.1
- Swift version: Swift 3
- iOS version: iOS 10.3
- Device: Both simulator and device
- Xcode version: Xcode 8.3.3
- My Podfile:
`target 'eNoticeIosApp' do`
  `use_frameworks!`

  `pod 'SwipeableTabBarController'`
  `pod 'Segmentio', '~> 2.1'`

  `target 'eNoticeIosAppTests' do`
    `inherit! :search_paths`
  `end`

  `target 'eNoticeIosAppUITests' do`
    `inherit! :search_paths`
  `end`

`end`

**Comment by freaqed** [comment]
Hi, @NortonWEI!
I just run the example project and tried to setup segmentio's height to be 50.
And it works for me. Btw, in `viewDidLoad` method of `ExampleViewController` it set automatically depending on current style.
I guess the problem you're describing is related to content layering. Try to setup your segmentio inside `viewDidLayoutSubview` method of your controller (but check it happen once).
If you still facing the issue reopen it and share some code and screenshots with us.
