### ISSUE TITLE
imageOverLabel style is Not working properly under navigation

### ISSUE THREAD

**Issue by AfrozZaheer** [Yalantis/Segmentio#66]
# Report

###  What did you do?
- I place segmentio view under Navigation and and setup with imageOverLabel 

### What did you expect to happen?

- It will work fine just like without navigation.

### What happened instead?

- Text label containing title hide and image get in center.

### Your Environment

- Version of the component: 2.1
- Swift version: 3.0
- iOS version: 10.3
- Device: iPhone 7
- Xcode version: 8.3.3

**Comment by freaqed** [comment]
Hi, @AfrozZaheer 
I'm not sure if it's related to Segmentio. Could you please share some screenshots?
And code of the component usage would be greate

**Comment by AfrozZaheer** [comment]
Hi, thanks for feed back I don't think the issue was with Segmentio it was with iOS 11. I was using navigation with bar tint  = false.. removing this and line it works fine.
