### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by bently93** [Yalantis/Segmentio#67]
Undefined symbols for architecture x86_64:
  "__TIFV9Segmentio13SegmentioItemcFT5titleGSqSS_5imageGSqCSo7UIImage_13selectedImageGSqS1___S0_A1_", referenced from:
      __TFC9icomarket27DetailICOMainViewController11viewDidLoadfT_T_ in DetailICOMainViewController.o
  "__TFV9Segmentio13SegmentioItemCfT5titleGSqSS_5imageGSqCSo7UIImage_13selectedImageGSqS1___S0_", referenced from:
      __TFC9icomarket27DetailICOMainViewController11viewDidLoadfT_T_ in DetailICOMainViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by freaqed** [comment]
Hello, @bently93 
I can't say anything from a stack you've listed above. Please share with us your code from `viewDidLoad` method of your `DetailICOMainViewController`

**Comment by rnkyr** [comment]
If this issue is still happening please let us know.
