### ISSUE TITLE
Segment View weird Placement if embedded inside the Tab bar Controller

### ISSUE THREAD

**Issue by KaushikShivam** [Yalantis/Segmentio#70]
# Report
![simulator screen shot 06-oct-2017 1 57 43 pm](https://user-images.githubusercontent.com/14944115/31269522-663c1660-aa9e-11e7-9573-afd3f7fc30fa.png)

**Comment by freaqed** [comment]
Hi, @KaushikShivam!
Please don't use Segmentio as a view for tab bar. Instead you should implement tabbar's logic by yourself. It looks weird since you're trying to display whole component inside single item, which is useless and not supposed to work because of item's layouting
