### ISSUE TITLE
iOS 11 - Items not tappable

### ISSUE THREAD

**Issue by grifas** [Yalantis/Segmentio#71]
# Report

###  What did you do?

> Use Segmentio in my app on iOS 11  

### What did you expect to happen?

> I expected to tap on each SegmentioItem .  

### What happened instead?

> SegmentioItems are not tappable.

### Your Environment

- Swift version: 3
- iOS version: 11
- Device: iPhone 6s
- Xcode version: Xcode 9

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 582d834782090c7284a93c0481cc50915ab788d5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Target' do
	pod 'Segmentio', '~> 2.1'
end

```

**Comment by grifas** [comment]
Ok I found the issue. It's because I embedded the segmentio view in a toolbar and I don't know why but on iOS 11, it's not tappable. I removed the toolbar and it works.

**Comment by toothpiggystudio** [comment]
Hi, I also tried inside the Scroll view and it's not tappable also, any solution on this one? :)
