### ISSUE TITLE
Autolayout issue using Segmentio programtically

### ISSUE THREAD

**Issue by engmsaleh** [Yalantis/Segmentio#8]
I use the `Segmentio` and add it programmatically. I use `PureLayout` to make the constrains.
I have made an autolayout view and add `Segmentio` as a subview to it.
I have constrained the height to be `150` on iPad.

When I run I got the following error

```
 Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
2016-10-03 21:24:57.844699 mobshop[2977:1277011] The behavior of the UICollectionViewFlowLayout is not defined because:
2016-10-03 21:24:57.844801 mobshop[2977:1277011] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2016-10-03 21:24:57.845131 mobshop[2977:1277011] The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x1969f2f0>, and it is attached to <UICollectionView: 0x153d0800; frame = (0 0; 512 200); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x196a0040>; layer = <CALayer: 0x1969f8d0>; contentOffset: {0, -64}; contentSize: {680, 136}> collection view layout: <UICollectionViewFlowLayout: 0x1969f2f0>. 
```

I have checked the example provided and it seems to do the same as me expect for that it is done using storyboard.

**Comment by serejahh** [comment]
Could you provide a test project?

**Comment by engmsaleh** [comment]
@serejahh Please find here an example project that I have made to reproduce the autolayout issue
https://github.com/engmsaleh/Segmentio-Purelayout-example
I think also there is another related issue, when you make the device to change orientation the Segmentio view isn't  updated with the new constrains until I click one of the section inside it and it give the following waning in console
`[App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction `

**Comment by serejahh** [comment]
Great, thanks! I'm having a look at the example app

**Comment by sam961** [comment]
Yes same here too, I added a scrollview and inside it I added a view and then I added a list of view with superclass Segmentio in the story board, it iw working fine but there is at the top and the bottom of the scroll view a horizontal line ... when deletingthe views of Segmentio the line disappears.
Also i face other problem when set Segmentio with a view and make layout for it... it doesnt appear

**Comment by houze2311** [comment]
@engmsaleh
We are working on solving this problem.
For a quick fix you must:

add function in Segmentio
```
open func interfaceOrientationDidChange() {
        segmentioCollectionView?.collectionViewLayout.invalidateLayout()
        scrollToItemAtContext()
        moveShapeLayerAtContext()
}
```

remove in Segmentio:
```
fileprivate var cachedOrientation: UIInterfaceOrientation? = UIApplication.shared.statusBarOrientation {
        didSet {
            if cachedOrientation != oldValue {
                reloadSegmentio()
            }
        }
  
}
```

and everything related to cachedOrientation:
```
@objc fileprivate func handleOrientationNotification() {
         cachedOrientation = UIApplication.shared.statusBarOrientation
}
```

```
NotificationCenter.default.addObserver(
            self,
            selector: #selector(Segmentio.handleOrientationNotification),
            name: NSNotification.Name.UIDeviceOrientationDidChange,
            object: nil
)
```

in function `commonInit`
```
deinit {
        NotificationCenter.default.removeObserver(self)
 }
```

override function `viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator)` in view controller
```
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        
        coordinator.animate(alongsideTransition: { [weak self] _ in
            self?.segmentioView.interfaceOrientationDidChange()
        }, completion: nil)
}
```

**Comment by bryanbartow** [comment]
I'm having a similar problem when rotating on iPad (rotating on iPhone seems fine). I'll try this fix and report back.

**Comment by bryanbartow** [comment]
The fix detailed by @houze2311 works for me.

**Comment by engmsaleh** [comment]
@houze2311 Thanks a lot for I will try it , When do you think you push it to a newer pod?

**Comment by houze2311** [comment]
Update .podspec to 2.1
