### ISSUE TITLE
Missing argument for parameter #1 in call UIView+Appearance modifier declared here

### ISSUE THREAD

**Issue by SoyArpad** [Yalantis/Segmentio#81]
# Report

###  What did you do?

im trying to compile the project 

### What happened instead?

appears a swift compiler error:

Missing argument for parameter #1 in call (UIView+Appearance.swift) with a warning of 'modifier' declared here

### Your Environment

- Version of the component: 2.1.2
- Swift version: 4.
- iOS version: 9.0+ (11 in emulator)
- Device: emulator iPhone 8
- Xcode version: Xcode 9.2
- If you use Cocoapods: 

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ef2021eb46a9856f89e7ade96cc7fc6928cc87e9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTarget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for MyTarget
  pod 'Alamofire', '~> 4.3'
  pod 'PureLayout'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftMessages'
  pod 'Segmentio'
end
```

**Comment by AhmadOdeh93** [comment]
I have the same issue with swift 4

**Comment by mud18** [comment]
Same issue while incorporating it in Swift4 project

**Comment by freaqed** [comment]
Hello guys @mud18, @AhmadOdeh93, and @SoyArpad!
The current version of Segmentio doesn't support Swift 4. It'll be added in a future release (can't say anything about timing).
Right now you can set `Swift Language Version` to `Swift 3 .2` in order to compile it (In Pods target of your project find `Segmentio` and open `Build Settings` tab).
Another (more automated) solution is to add this code snippet to your `Podfile`:
```
# configure pod's Swift version
post_install do |installer|
    myTargets = ['Segmentio']
    
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```
