### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by r-a-o** [Yalantis/Segmentio#82]
I am interested in using just the Side Bar implementation of this app, is there a repo/branch with just this implementation? (if not, please help me create one by listing down all the relevant files below?)

I have already checked out [Side-Menu.iOS](https://github.com/Yalantis/Side-Menu.iOS) which is a nice implementation of side bar but doesn't have the darker background and swipe gestures.

**Comment by Vodolazkyi** [comment]
Hi, we don't have repo/branch only with side bar implementation. You can fork and make changes according your needs. Thanks !
