### ISSUE TITLE
Indicator view Fixed size first cell

### ISSUE THREAD

**Issue by AlexanderBaranowski** [Yalantis/Segmentio#86]
Hello!

Found a little mistake, please adjust

Segmentio/Segmentio/Source/Segmentio.swift

lines 725...729
 `if context.isFirstCell == true {

                startX = (cellWidth - item.shapeLayerWidth) / 2
                startX = 0
                endX = startX + item.shapeLayerWidth
            }`

**Comment by grifas** [comment]
I get the same problem, and remove `startX = 0` on line 727 corrected it

**Comment by grifas** [comment]
I made you a PR to fix this : https://github.com/Yalantis/Segmentio/pull/99
