### ISSUE TITLE
RTL bug? selecting right one but indicator appear at left one

### ISSUE THREAD

**Issue by farshadjahanmanesh** [Yalantis/Segmentio#91]
# Report
## Report a bug
![simulator screen shot - iphone x - 2018-04-20 at 22 58 13](https://user-images.githubusercontent.com/13612410/39067889-8e60d4fa-44ef-11e8-9349-a11c1482b2bd.png)

###  What did you do?

> UIView.appearance().semanticContentAttribute = .forceRightToLeft
when I touch a segment from right, indicator appear bottom of left segment, and when I touch left one, right one will select.

### What did you expect to happen?

> I want to  use semanticContentAttribute = .forceRightToLeft and my app is RTL always. 

### What happened instead?

> when I touch a segment from right, indicator appear bottom of left segment, and when I touch left one, right one will select.

### Your Environment

- Version of the component: 3
- Swift version: 4.1
- iOS version: 11.3
- Device: iPhone x
- Xcode version: 9.3

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b170ef525bdc2c178e39a2f71fea99fbf10b121a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

platform :ios, ‘9’
use_frameworks!
target ‘optimus’ do
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.4'
  pod 'SDWebImage', '~>3.8’
  pod 'ActionSheetPicker-3.0'
  pod 'UIColor_Hex_Swift', '~> 3.0.2'
  pod 'Whisper','~> 6'
  pod 'FontAwesome.swift'
  pod 'Eureka'
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'SimpleAlert'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
  pod 'Hero'
  pod 'Gifu'
  pod 'ImageSlideshow', '~> 1.5'
  pod 'ImageSlideshow/Alamofire'
  pod 'Segmentio'
end
target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
```

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by rnkyr** [comment]
Hello, @farshadjahanmanesh 
Unfortunately, Segmentio doesn't suppose to support RTL
In case you managed to solve your problem please feel free to share the solution or even open a PR so other people could use it. Thanks!
