### ISSUE TITLE
Wrong layout of indicator when scroll to right

### ISSUE THREAD

**Issue by jvcol** [Yalantis/Segmentio#94]
###  What did you do?

Open the example project and change the maxVisibleItems to 4, then run the app. 

### What did you expect to happen?

The indicator is shown in correct position when scroll right

### What happened instead?

![may-21-2018 17-42-30](https://user-images.githubusercontent.com/4465590/40301804-c9cfbde2-5d1f-11e8-8302-0269d40460fa.gif)

### Your Environment

- Version of the component: 3.0
- Swift version: 4.1
- iOS version: 11.3
- Device: iOS Simulator, iPhone X
- Xcode version: 9.3.1

**Comment by SerjOxo** [comment]
@jvcol Hi! Thanks for your report. It will be fixed as soon as possible.
